### ISSUE TITLE
npm test error

### ISSUE THREAD

**Issue by sandervanhooft** [MaksTr/meteor-mantra-kickstarter#35]
Hi,

When running `npm test` I get the error message below. It seems to be caused by
`mocha .scripts/mocha_boot.js client/**/tests/**/*.js --compilers js:babel-core/register`
which is triggered by `npm run testonly`. Anyone else having this problem?

I have updated node and npm, but this has not resolved the issue. I also have tried a fresh kickstarter clone, same results.

```
...
  41 passing (705ms)
  9 pending
  1 failing

  1) _template.components.template should display the name title:
     ReferenceError: title is not defined
      at _class.render (template.jsx:10:14)
      at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (node_modules/react/lib/ReactCompositeComponent.js:587:34)
      at [object Object].ReactCompositeComponentMixin.mountComponent (node_modules/react/lib/ReactCompositeComponent.js:220:30)
      at [object Object].wrapper [as mountComponent] (node_modules/react/lib/ReactPerf.js:66:21)
      at [object Object].ReactShallowRenderer._render (node_modules/react/lib/ReactTestUtils.js:366:14)
      at _batchedRender (node_modules/react/lib/ReactTestUtils.js:348:12)
      at ReactDefaultBatchingStrategyTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:136:20)
      at Object.ReactDefaultBatchingStrategy.batchedUpdates (node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
      at Object.batchedUpdates (node_modules/react/lib/ReactUpdates.js:94:20)
      at [object Object].ReactShallowRenderer.render (node_modules/react/lib/ReactTestUtils.js:343:16)
      at [object Object].render (node_modules/enzyme/build/react-compat.js:146:39)
      at new ShallowWrapper (node_modules/enzyme/build/ShallowWrapper.js:81:21)
      at shallow (node_modules/enzyme/build/shallow.js:21:10)
      at Context.<anonymous> (template.js:10:16)




npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.9.0/bin/node" "/usr/local/bin/npm" "run" "testonly"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! mantra-demo@0.2.1 testonly: `mocha .scripts/mocha_boot.js client/**/tests/**/*.js --compilers js:babel-core/register`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mantra-demo@0.2.1 testonly script 'mocha .scripts/mocha_boot.js client/**/tests/**/*.js --compilers js:babel-core/register'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mantra-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha .scripts/mocha_boot.js client/**/tests/**/*.js --compilers js:babel-core/register
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mantra-demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mantra-demo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Sander/Desktop/temp/meteor-mantra-kickstarter/npm-debug.log
```

**Comment by sandervanhooft** [comment]
Fixed this, don't know how exactly. Probably by updating mocha.
